# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20161224_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbody',
            name='blog_abstract',
            field=models.TextField(default=datetime.datetime(2017, 1, 16, 3, 28, 10, 413000, tzinfo=utc), verbose_name='\u6458\u8981'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogbody',
            name='blog_is_top',
            field=models.BooleanField(default=False, verbose_name='\u7f6e\u9876'),
        ),
        migrations.AddField(
            model_name='blogbody',
            name='blog_tags',
            field=models.CharField(blank=True, help_text='\u7528\u9017\u53f7\u5206\u9694', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogbody',
            name='blog_update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 16, 3, 28, 17, 269000, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogbody',
            name='blog_author',
            field=models.CharField(max_length=20, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='blogbody',
            name='blog_body',
            field=models.TextField(verbose_name='\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='blogbody',
            name='blog_clicknum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogbody',
            name='blog_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogbody',
            name='blog_timestamp',
            field=models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='blogbody',
            name='blog_title',
            field=models.CharField(max_length=100, verbose_name='\u6807\u9898'),
        ),
    ]
